import {
  type InvariantTest,
  type ExecutionContext,
  type InvariantResult,
  MicrosecondBurstDispatcher,
} from '@acid-test/core';

export class StructuredOutputPoisoningTest implements InvariantTest {
  id = 'ACID-AI-002';
  name = 'Structured Output Schema Poisoning & Malformed JSON Fuzzer';
  category = 'ai';
  provider = 'openai';
  severity = 'HIGH' as const;
  description = 'Simulates malformed LLM outputs (markdown-wrapped JSON, trailing commas, stringified numbers) to verify fallback parsing without 500 crashes.';

  async run(context: ExecutionContext): Promise<InvariantResult> {
    const startTime = Date.now();
    const targetUrl = context.targetUrl || 'http://localhost:3000/api/generate/structured';

    // Markdown-wrapped JSON output often generated by LLMs
    const markdownWrappedJson = '```json\n{\n  "title": "Report",\n  "count": 42,\n}\n```';

    const res = await MicrosecondBurstDispatcher.dispatch({
      url: targetUrl,
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ rawLlmResponse: markdownWrappedJson }),
      concurrency: 1,
    });

    const status = res.responses[0]?.statusCode || 0;
    const passed = status < 500;

    return {
      testId: this.id,
      testName: this.name,
      category: this.category,
      provider: this.provider,
      severity: this.severity,
      status: passed ? 'PASS' : 'FAIL',
      durationMs: Date.now() - startTime,
      title: 'Structured Output Markdown & Malformed JSON Resilience',
      summary: passed
        ? 'Schema parser successfully extracted JSON from markdown block without unhandled server exception.'
        : 'SCHEMA CRASH: Server threw unhandled 500 error when parsing markdown-wrapped or trailing-comma JSON.',
      failingFile: 'lib/ai/parser.ts',
      lineNumber: 10,
      rootCause: 'JSON.parse called directly on LLM output without stripping ```json markdown fences or trailing commas.',
      suggestedFix: 'Sanitize LLM output with regex `text.replace(/```json\\s*|```/g, "").trim()` before schema validation.',
      aiPrompt: 'In lib/ai/parser.ts, sanitize raw LLM text by stripping markdown code blocks before JSON parsing.',
    };
  }
}
